pipeline{
    agent any
    tools
    {
        nodejs "Node-18"
    }

    stages{
        stage("Fetch Code"){
            steps{
                git branch: 'main' , url:'https://github.com/Utkarshnegi2k5/GoGreen1.git'
            }
        }

        stage("Installing tools"){
            steps{
                sh 'npm install'
            }
        }
        
        stage("Check Python"){
            steps{
                sh 'python3 --version'
            }
        }

        stage("Precheck"){
            steps{
                sh 'python3 pipeline/precheck.py'
            }
        }
    }
}